spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/miti}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: ${PORT:33500}

jwt:
  secret: MITI_secret-key
